---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  become: true

- name: Ensure EPICS packages are installed
  apt:
    name: "{{ epics_packages }}"
    state: "{{ epics_packages_state }}"
    install_recommends: "{{ epics_install_recommends }}"
  become: true
  register: apt_packages_result
  until: apt_packages_result is success
  retries: 10
  delay: 2
